// <auto-generated />
using System;
using DB.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20250827233435_FixNullsUsuario")]
    partial class FixNullsUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ENTIDAD.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("apellido");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("CONTACTO");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_rol");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("razon_social");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UsCedula")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("US_Cedula");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.Auditorium", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_auditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_accion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdAuditoria")
                        .HasName("PK__Auditori__9644A3CED1A46BA2");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_Auditoria_id_usuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Models.BitacoraMuestra", b =>
                {
                    b.Property<long>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_bitacora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdBitacora"));

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdAnalista")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_analista");

                    b.Property<string>("IdMuestra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id_muestra");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdBitacora")
                        .HasName("PK__Bitacora__7E4268B0BAD2A82E");

                    b.HasIndex(new[] { "IdAnalista" }, "IX_Bitacora_Muestra_id_analista");

                    b.HasIndex(new[] { "IdMuestra" }, "IX_Bitacora_Muestra_id_muestra");

                    b.ToTable("Bitacora_Muestra", (string)null);
                });

            modelBuilder.Entity("Models.Documento", b =>
                {
                    b.Property<long>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDocumento"));

                    b.Property<byte[]>("DocPdf")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("DOC_PDF");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdMuestra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id_muestra");

                    b.Property<byte>("IdTipoDoc")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_tipo_doc");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ruta_archivo");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("IdDocumento")
                        .HasName("PK__Document__5D2EE7E5FCF72C46");

                    b.HasIndex("IdTipoDoc");

                    b.HasIndex(new[] { "IdMuestra" }, "IX_Documento_id_muestra");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("Models.EstadoMuestra", b =>
                {
                    b.Property<byte>("IdEstado")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstado")
                        .HasName("PK__Estado_M__86989FB231F3242F");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Estado_M__72AFBCC62E07FBCF")
                        .IsUnique();

                    b.ToTable("Estado_Muestra", (string)null);
                });

            modelBuilder.Entity("Models.HistorialTrazabilidad", b =>
                {
                    b.Property<long>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdHistorial"));

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_cambio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdMuestra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id_muestra");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdHistorial")
                        .HasName("PK__Historia__76E6C5025A7F6AE1");

                    b.HasIndex("Estado");

                    b.HasIndex(new[] { "IdMuestra" }, "IX_Historial_Trazabilidad_id_muestra");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_Historial_Trazabilidad_id_usuario");

                    b.ToTable("Historial_Trazabilidad", (string)null);
                });

            modelBuilder.Entity("Models.Muestra", b =>
                {
                    b.Property<string>("MstCodigo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MST_CODIGO");

                    b.Property<string>("CondicionesAlmacenamiento")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Condiciones_almacenamiento");

                    b.Property<string>("CondicionesTransporte")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Condiciones_transporte");

                    b.Property<byte>("EstadoActual")
                        .HasColumnType("tinyint")
                        .HasColumnName("estado_actual");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_recepcion");

                    b.Property<DateTime?>("FechaSalidaEstimada")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Salida_Estimada");

                    b.Property<string>("IdAnalista")
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_Analista");

                    b.Property<string>("IdUsuarioSolicitante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_usuario_solicitante");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("origen");

                    b.Property<byte>("TpmstId")
                        .HasColumnType("tinyint")
                        .HasColumnName("TPMST_ID");

                    b.HasKey("MstCodigo")
                        .HasName("PK__Muestra__800EDF4D8255C508");

                    b.HasIndex("EstadoActual");

                    b.HasIndex("IdAnalista");

                    b.HasIndex("IdUsuarioSolicitante");

                    b.HasIndex("TpmstId");

                    b.HasIndex(new[] { "FechaRecepcion", "FechaSalidaEstimada" }, "idx_muestra_fechas");

                    b.ToTable("Muestra", (string)null);
                });

            modelBuilder.Entity("Models.Notificacion", b =>
                {
                    b.Property<long>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_notificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdNotificacion"));

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("destinatario");

                    b.Property<string>("Detalle")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("detalle");

                    b.Property<bool>("Enviado")
                        .HasColumnType("bit")
                        .HasColumnName("enviado");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_envio");

                    b.Property<string>("IdMuestra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id_muestra");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("tipo_alerta");

                    b.HasKey("IdNotificacion")
                        .HasName("PK__Notifica__8270F9A50C4940E9");

                    b.HasIndex(new[] { "IdMuestra" }, "IX_Notificacion_id_muestra");

                    b.ToTable("Notificacion", (string)null);
                });

            modelBuilder.Entity("Models.ParametroNorma", b =>
                {
                    b.Property<int>("IdParametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_parametro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametro"));

                    b.Property<int>("IdPrueba")
                        .HasColumnType("int")
                        .HasColumnName("id_prueba");

                    b.Property<string>("NombreParametro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre_parametro");

                    b.Property<string>("Unidad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("unidad");

                    b.Property<decimal?>("ValorMax")
                        .HasColumnType("decimal(18, 6)")
                        .HasColumnName("valor_max");

                    b.Property<decimal?>("ValorMin")
                        .HasColumnType("decimal(18, 6)")
                        .HasColumnName("valor_min");

                    b.HasKey("IdParametro")
                        .HasName("PK__Parametr__3D24E3256A0410FE");

                    b.HasIndex(new[] { "IdPrueba", "NombreParametro" }, "uk_parametro")
                        .IsUnique();

                    b.ToTable("Parametro_Norma", (string)null);
                });

            modelBuilder.Entity("Models.Prueba", b =>
                {
                    b.Property<int>("IdPrueba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_prueba");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrueba"));

                    b.Property<string>("NombrePrueba")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre_prueba");

                    b.Property<string>("NormaReferencia")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("norma_referencia");

                    b.Property<byte>("TipoMuestraAsociada")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo_muestra_asociada");

                    b.HasKey("IdPrueba")
                        .HasName("PK__Prueba__328A4573149CBD98");

                    b.HasIndex("TipoMuestraAsociada");

                    b.HasIndex(new[] { "NombrePrueba", "TipoMuestraAsociada" }, "uk_prueba")
                        .IsUnique();

                    b.ToTable("Prueba", (string)null);
                });

            modelBuilder.Entity("Models.ResultadoPrueba", b =>
                {
                    b.Property<long>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_resultado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdResultado"));

                    b.Property<bool?>("CumpleNorma")
                        .HasColumnType("bit")
                        .HasColumnName("cumple_norma");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdMuestra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id_muestra");

                    b.Property<int>("IdPrueba")
                        .HasColumnType("int")
                        .HasColumnName("id_prueba");

                    b.Property<string>("Unidad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("unidad");

                    b.Property<string>("ValidadoPor")
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("validado_por");

                    b.Property<decimal?>("ValorObtenido")
                        .HasColumnType("decimal(18, 6)")
                        .HasColumnName("valor_obtenido");

                    b.HasKey("IdResultado")
                        .HasName("PK__Resultad__33A42B30FAD681EE");

                    b.HasIndex("ValidadoPor");

                    b.HasIndex(new[] { "IdMuestra" }, "IX_Resultado_Prueba_id_muestra");

                    b.HasIndex(new[] { "IdPrueba" }, "IX_Resultado_Prueba_id_prueba");

                    b.HasIndex(new[] { "IdMuestra", "FechaRegistro" }, "idx_resultado_muestra_fecha");

                    b.ToTable("Resultado_Prueba", (string)null);
                });

            modelBuilder.Entity("Models.RolUsuario", b =>
                {
                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol_Usua__6ABCB5E0C2370F5E");

                    b.HasIndex(new[] { "NombreRol" }, "UQ__Rol_Usua__673CB435C9C52528")
                        .IsUnique();

                    b.ToTable("Rol_Usuario", (string)null);
                });

            modelBuilder.Entity("Models.TipoDocumento", b =>
                {
                    b.Property<byte>("IdTipoDoc")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_tipo_doc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoDoc")
                        .HasName("PK__Tipo_Doc__B0A524EA001DA409");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Tipo_Doc__72AFBCC67DC151A6")
                        .IsUnique();

                    b.ToTable("Tipo_Documento", (string)null);
                });

            modelBuilder.Entity("Models.TipoMuestra", b =>
                {
                    b.Property<byte>("TpmstId")
                        .HasColumnType("tinyint")
                        .HasColumnName("TPMST_ID");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre");

                    b.HasKey("TpmstId")
                        .HasName("PK__Tipo_Mue__3DB040A8B6354D0C");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Tipo_Mue__72AFBCC6EAC23A93")
                        .IsUnique();

                    b.ToTable("Tipo_Muestra", (string)null);
                });

            modelBuilder.Entity("ENTIDAD.Models.Usuario", b =>
                {
                    b.HasOne("Models.RolUsuario", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ENTIDAD.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ENTIDAD.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENTIDAD.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ENTIDAD.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Auditorium", b =>
                {
                    b.HasOne("ENTIDAD.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Auditoria")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_aud_usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Models.BitacoraMuestra", b =>
                {
                    b.HasOne("ENTIDAD.Models.Usuario", "IdAnalistaNavigation")
                        .WithMany("BitacoraMuestras")
                        .HasForeignKey("IdAnalista")
                        .IsRequired()
                        .HasConstraintName("fk_bit_analista");

                    b.HasOne("Models.Muestra", "IdMuestraNavigation")
                        .WithMany("BitacoraMuestras")
                        .HasForeignKey("IdMuestra")
                        .IsRequired()
                        .HasConstraintName("fk_bit_muestra");

                    b.Navigation("IdAnalistaNavigation");

                    b.Navigation("IdMuestraNavigation");
                });

            modelBuilder.Entity("Models.Documento", b =>
                {
                    b.HasOne("Models.Muestra", "IdMuestraNavigation")
                        .WithMany("Documentos")
                        .HasForeignKey("IdMuestra")
                        .IsRequired()
                        .HasConstraintName("fk_doc_muestra");

                    b.HasOne("Models.TipoDocumento", "IdTipoDocNavigation")
                        .WithMany("Documentos")
                        .HasForeignKey("IdTipoDoc")
                        .IsRequired()
                        .HasConstraintName("fk_doc_tipodoc");

                    b.Navigation("IdMuestraNavigation");

                    b.Navigation("IdTipoDocNavigation");
                });

            modelBuilder.Entity("Models.HistorialTrazabilidad", b =>
                {
                    b.HasOne("Models.EstadoMuestra", "EstadoNavigation")
                        .WithMany("HistorialTrazabilidads")
                        .HasForeignKey("Estado")
                        .IsRequired()
                        .HasConstraintName("fk_ht_estado");

                    b.HasOne("Models.Muestra", "IdMuestraNavigation")
                        .WithMany("HistorialTrazabilidads")
                        .HasForeignKey("IdMuestra")
                        .IsRequired()
                        .HasConstraintName("fk_ht_muestra");

                    b.HasOne("ENTIDAD.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("HistorialTrazabilidads")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_ht_usuario");

                    b.Navigation("EstadoNavigation");

                    b.Navigation("IdMuestraNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Models.Muestra", b =>
                {
                    b.HasOne("Models.EstadoMuestra", "EstadoActualNavigation")
                        .WithMany("Muestras")
                        .HasForeignKey("EstadoActual")
                        .IsRequired()
                        .HasConstraintName("fk_muestra_estado");

                    b.HasOne("ENTIDAD.Models.Usuario", "IdAnalistaNavigation")
                        .WithMany("MuestraIdAnalistaNavigations")
                        .HasForeignKey("IdAnalista")
                        .HasConstraintName("fk_muestra_analista");

                    b.HasOne("ENTIDAD.Models.Usuario", "IdUsuarioSolicitanteNavigation")
                        .WithMany("MuestraIdUsuarioSolicitanteNavigations")
                        .HasForeignKey("IdUsuarioSolicitante")
                        .IsRequired()
                        .HasConstraintName("fk_muestra_solic");

                    b.HasOne("Models.TipoMuestra", "Tpmst")
                        .WithMany("Muestras")
                        .HasForeignKey("TpmstId")
                        .IsRequired()
                        .HasConstraintName("fk_muestra_tipo");

                    b.Navigation("EstadoActualNavigation");

                    b.Navigation("IdAnalistaNavigation");

                    b.Navigation("IdUsuarioSolicitanteNavigation");

                    b.Navigation("Tpmst");
                });

            modelBuilder.Entity("Models.Notificacion", b =>
                {
                    b.HasOne("Models.Muestra", "IdMuestraNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdMuestra")
                        .IsRequired()
                        .HasConstraintName("fk_not_muestra");

                    b.Navigation("IdMuestraNavigation");
                });

            modelBuilder.Entity("Models.ParametroNorma", b =>
                {
                    b.HasOne("Models.Prueba", "IdPruebaNavigation")
                        .WithMany("ParametroNormas")
                        .HasForeignKey("IdPrueba")
                        .IsRequired()
                        .HasConstraintName("fk_parnorma_prueba");

                    b.Navigation("IdPruebaNavigation");
                });

            modelBuilder.Entity("Models.Prueba", b =>
                {
                    b.HasOne("Models.TipoMuestra", "TipoMuestraAsociadaNavigation")
                        .WithMany("Pruebas")
                        .HasForeignKey("TipoMuestraAsociada")
                        .IsRequired()
                        .HasConstraintName("fk_prueba_tipo");

                    b.Navigation("TipoMuestraAsociadaNavigation");
                });

            modelBuilder.Entity("Models.ResultadoPrueba", b =>
                {
                    b.HasOne("Models.Muestra", "IdMuestraNavigation")
                        .WithMany("ResultadoPruebas")
                        .HasForeignKey("IdMuestra")
                        .IsRequired()
                        .HasConstraintName("fk_res_muestra");

                    b.HasOne("Models.Prueba", "IdPruebaNavigation")
                        .WithMany("ResultadoPruebas")
                        .HasForeignKey("IdPrueba")
                        .IsRequired()
                        .HasConstraintName("fk_res_prueba");

                    b.HasOne("ENTIDAD.Models.Usuario", "ValidadoPorNavigation")
                        .WithMany("ResultadoPruebas")
                        .HasForeignKey("ValidadoPor")
                        .HasConstraintName("fk_res_validador");

                    b.Navigation("IdMuestraNavigation");

                    b.Navigation("IdPruebaNavigation");

                    b.Navigation("ValidadoPorNavigation");
                });

            modelBuilder.Entity("ENTIDAD.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("BitacoraMuestras");

                    b.Navigation("HistorialTrazabilidads");

                    b.Navigation("MuestraIdAnalistaNavigations");

                    b.Navigation("MuestraIdUsuarioSolicitanteNavigations");

                    b.Navigation("ResultadoPruebas");
                });

            modelBuilder.Entity("Models.EstadoMuestra", b =>
                {
                    b.Navigation("HistorialTrazabilidads");

                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("Models.Muestra", b =>
                {
                    b.Navigation("BitacoraMuestras");

                    b.Navigation("Documentos");

                    b.Navigation("HistorialTrazabilidads");

                    b.Navigation("Notificacions");

                    b.Navigation("ResultadoPruebas");
                });

            modelBuilder.Entity("Models.Prueba", b =>
                {
                    b.Navigation("ParametroNormas");

                    b.Navigation("ResultadoPruebas");
                });

            modelBuilder.Entity("Models.RolUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Models.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Models.TipoMuestra", b =>
                {
                    b.Navigation("Muestras");

                    b.Navigation("Pruebas");
                });
#pragma warning restore 612, 618
        }
    }
}
